const OpencgaJobsBrowserConfig = {
    /*title: "Jobs Browser",
    icon: "fas fa-chart-bar",
    description: "",
    searchButtonText: "Run",
    views: [
        {
            id: "table-tab",
            name: "Table result",
            active: true
        },
        {
            id: "facet-tab",
            name: "Aggregation stats"
        },/!*
                {
                    id: "comparator-tab",
                    name: "Comparator"
                },*!/
        {
            id: "visual-browser-tab",
            name: "Visual browser"
        }
    ],
    filter: {
        sections: [
            {
                title: "Section title",
                collapsed: false,
                fields: [
                    {
                        id: "id",
                        name: "Job ID",
                        placeholder: "ID",
                        allowedValues: "",
                        defaultValue: "",
                        description: "Job ID. It must be a unique string within the study. An id will be autogenerated automatically if not provided.",
                        fileUpload: false
                    },
                    {
                        id: "tool",
                        name: "Analysis Tool ID",
                        placeholder: "Tool",
                        allowedValues: "",
                        defaultValue: "",
                        description: "Tool executed by the job"
                    },
                    {
                        id: "input",
                        name: "Input File Name",
                        placeholder: "e.g.  NA12877.vcf.gz",
                        allowedValues: "",
                        defaultValue: "",
                        description: "File used by the Tool",
                        fileUpload: false
                    },
                    {
                        id: "internal.status.name",
                        name: "Status",
                        placeholder: "Status",
                        allowedValues: ["PENDING", "QUEUED", "RUNNING", "DONE", "ERROR", "UNKNOWN", "REGISTERING", "UNREGISTERED", "ABORTED", "DELETED"],
                        defaultValue: "",
                        description: "Job internal status"
                    },
                    {
                        id: "priority",
                        name: "Priority",
                        placeholder: "Priority",
                        allowedValues: ["URGENT", "HIGH", "MEDIUM", "LOW"],
                        defaultValue: "",
                        description: "Priority of the job"
                    },
                    {
                        id: "tags",
                        name: "Tags",
                        placeholder: "Tags",
                        allowedValues: "",
                        defaultValue: "",
                        description: "Job tags"
                    },
                    {
                        id: "creationDate",
                        name: "Creation Date",
                        placeholder: "Creation Date",
                        description: "Creation date. Format: yyyyMMddHHmmss. Examples: >2018, 2017-2018, <201805"
                    },
                    {
                        id: "visited",
                        name: "Visited",
                        placeholder: "Visited",
                        allowedValues: ["true", "false"],
                        defaultValue: "",
                        description: "Visited status of job"
                    },
                ]
            }
        ],
        examples: [
            {
                name: "Full",
                active: false,
                query: {
                    name: "bam",
                    path: "genomes",
                    sample: "hg3333",
                    format: "VCF,BCF,GVCF,BIGWIG",
                    bioformat: "ALIGNMENT",
                    creationDate: ">=20200216"
                }
            }
        ],
        result: {
            grid: {}
        },
        detail: [
            {
                id: "job-detail",
                title: "Details",
                active: true
            },
            {
                id: "log",
                title: "Log"
            }
        ]
    },
    aggregation: {
        default: ["type", "study>>bioformat"],
        result: {
            numColumns: 2
        },
        sections: [
            {
                name: "Section Title",
                // collapsed: false,
                fields: [
                ]
            }
        ]
    }*/
};
